### In this notebook we will look at

random module

array manipulations

In [2]:
import numpy as np

In [3]:
# random.rand(x) will return an ndarray with x number of items that are 
# randomly selected between 0 and 1
a = np.random.rand(3)
print(a)

[0.66499813 0.18422214 0.2409968 ]


In [4]:
"""
using sort() to sort the elements in an ndarrray
sort(axis, kind)
all arguments are optional
axis can be specified, default -1 means sort along the last axis

kind can be quicksort, mergesort or heapsort. Default is quicksort
"""

a.sort() 
print(a)

[0.18422214 0.2409968  0.66499813]


In [5]:
# random.sample will return a random number from a uniform distribution from [0.0, 1.0)
# 1.0 is not included
c = np.random.sample()
print(c)

0.7889797048033659


In [6]:
# random.choice(n) will return a number from an ndarray n
a = np.array([2, 6, 12, 18])
print(np.random.choice(a))

6


In [7]:
"""
random.randint(x) will return an integer from the interval  [0, x], both are included
random.randint(x, y) will return an integer from [x, y]
random.randint(x, y, n) will return n integers between x and y
"""

print(np.random.randint(5))
print(np.random.randint(11, 15))
print(np.random.randint(-10, -5, 2))

3
14
[-7 -9]


In [11]:
"""
In-class activity: 
From the list ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"] choose a name
"""
print(np.random.choice(["Elizabeth", "Lisa", "Asha", "Mike", "Amit"]))

Lisa


In [12]:
"""
In-class activity:
Using random.rand create a 1D ndarray, then convert the values in the ndarray to integer 
and then choose a value from the new int adarray. At every step print the output. 

"""
a = np.random.rand(2,2)*5
print(a)


[[1.83231357 2.47835955]
 [3.15504756 4.84067398]]


#### Now we will look at the array manipulation

In [8]:
a = np.array([[2, 4], [7, 9]])
b = np.array([[1, 3], [6, 5]])
print(a)
print(b)
print(a @ b)

[[2 4]
 [7 9]]
[[1 3]
 [6 5]]
[[26 26]
 [61 66]]


In [9]:
# using + operator we can compute element by element sum of two arrays
print(a + b)

[[ 3  7]
 [13 14]]


In [10]:
# using * operator we can compute element by element multiplication of two arrays

print(a * b) # element by element multiplication

[[ 2 12]
 [42 45]]


In [11]:
# using - operator we can compute element by element subtraction of two arrays

print(a - b)

[[1 1]
 [1 4]]


In [12]:
# dot(a1, a2) will compute matrix multiplication

print(np.dot(a, b)) # matrix multiplication 

[[26 26]
 [61 66]]


In [13]:
# @ can be used to perform matrix multiplication 
# @  is called the 'infix' operator and is only available in Python 3.5+ (PEP 465)

print(a @ b) 

[[26 26]
 [61 66]]


In [14]:
# if we have matrices then we can perfrom matrix multiplication using matmul(a1, a2)

print(np.matmul(a, b)) # matrix multiplication

[[26 26]
 [61 66]]


In [15]:
# in an array transpose() will interchange the rows to columns 
# and vice-versa 

print(np.transpose([[4, 7, 9], [5, 7, 10]]))

[[ 4  5]
 [ 7  7]
 [ 9 10]]


In [16]:
# T can also be used to transpose a matrix

y = np.array([[3, 5], [8, 11]])
print(y)
print(y.T)

[[ 3  5]
 [ 8 11]]
[[ 3  8]
 [ 5 11]]


In [22]:
"""
In-class activity:
Create two 2-by-2 ndarrays. Compute the following:

1) Element by element multiplication

2) Array multiplication using two different methods
"""
arr1 = np.array(([1,2], [3,4]))
arr2 = np.array(([5,6], [7,8]))
print(f'arr1{arr1} * arr2{arr2} = {arr1 * arr2}')
print(arr1 * arr2)
print(arr1 @ arr2)
print(np.matmul(arr1, arr2))

arr1[[1 2]
 [3 4]] * arr2[[5 6]
 [7 8]] = [[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [33]:
"""
In-class activity:
Create an 2-by-2 ndarray. Compute the following:

1) Transpose of the ndarray

2) array multiplication of the old array and the transposed array
"""

arr = np.array(([1,2],[3,4]))
print(arr)
print(f'array transposed = ')

transposed = arr.T
print(transposed)
print(f'arr @ trans = ')
print(arr @ transposed)
print(f'arr * trans = ')
print(arr * transposed)

[[1 2]
 [3 4]]
array transposed = 
[[1 3]
 [2 4]]
arr @ trans = 
[[ 5 11]
 [11 25]]
arr * trans = 
[[ 1  6]
 [ 6 16]]
