In this notebook we will discuss reading and writing files using numpy.

We will look at

csv

pickle

npy

In [1]:
import numpy as np

In [2]:
d = np.array([[10, 15, 12], [7, 16, 30], [19, 45, 70]])

In [4]:
# write the vector d to a csv file with 3 precision

d.tofile(file="data.csv", sep=",", format="%0.3f")

In [5]:
# genfromtxt(filename, delimiter) can be used to read several file formats

rd = np.genfromtxt("data.csv", delimiter=",")
print(rd)

[10. 15. 12.  7. 16. 30. 19. 45. 70.]


#### Pickle file

pickle file is a file format that follows first in first out and 
the objects are stored in the binary format

In [6]:
# b.dump(filename) is used to write b to the file that is specified in the parantheses

d.dump("data.pickle") # write d to a pickle file

#### npy file

Is a binary file format to store numpy objects

In [7]:
a = np.array([[2, 3, 11], [-5, 9, 19]])
print(a)

[[ 2  3 11]
 [-5  9 19]]


In [8]:
# using save(filename, object) we can save a particular object in the specified file

np.save('d1.npy', a) 

In [9]:
# using load(filename) we can read all the objects sequentially from the file

np.load('d1.npy')

array([[ 2,  3, 11],
       [-5,  9, 19]])

In [10]:
# saving multiple objects in a npy file

b = np.array(["JJ", "AX", "BY"])
np.save('d2.npy', [a, b]) 

In [11]:
np.load("d2.npy")

ValueError: Object arrays cannot be loaded when allow_pickle=False

#### More operations using genfromtxt()

#### Python io module 

io module is used to deal with various I/O types. 

There are 3 main i/o types:
    1) text
    
    2) binary
    
    3) raw
    
Modes are:
    1) read-only
    
    2) write-only
    
    3) read-write
    
We will look at StringIO - is very efficient to create large strings

In [46]:
from io import StringIO

In [54]:
out = StringIO() 

In [55]:
print("Watermelon", file=out, end="")

In [56]:
print(out.getvalue())

Watermelon


In [63]:
# Writing to a file

out = StringIO()


for i in range(0, 5):
    out.write(str(i))
    out.write(" ")

data = out.getvalue()
print(data)
out.close()

0 1 2 3 4 


In [ ]:
"""
In-class activity:

Create text file with 5 state names. Open the text file and print 
the contents of the file.
"""

In [ ]:
"""
In-class activity:

We have a string "There can only be one winner"

use StringIO to write the string and then print the string.

"""

In [ ]:
"""
In-class activity:

Create npy file and save two ndarrays in it. Print the values from file.
"""
